#!/bin/bash

tname=""
read -p "Release Name:" tname 

git tag -a $tname
gh release create $tname
./export_files.sh
zip Gerbers.zip Gerbers_and_Drill/*
gh release upload $tname Gerbers.zip 3D/* Schematic/sch.pdf Manufacturers/JLC.zip
rm Gerbers.zip
